## NumPy

NumPy (сокращенно от Numerical Python)— библиотека с открытым исходным кодом для языка программирования Python. 

Возможности:

* поддержка многомерных массивов (включая матрицы);
* поддержка высокоуровневых математических функций, предназначенных для работы с многомерными массивами.

[Документация](https://numpy.org/doc/stable/user/index.html#user)

#### Установка

In [2]:
# !pip install numpy

#### Импорт

In [5]:
import numpy as np

#### ndarray

![Изображение](https://laboputer.github.io/assets/img/ml/python/numpy/1.JPG)
    
Массив — упорядоченная изменяемая структура данных, к элементам которой можно обратиться по индексу

Основной объект NumPy является **ndarray** (n-dimensional array) - многомерный однородный массив с заранее заданным количеством элементов. 
* все объекты в нем одного размера или типа (тип данных определен другим объектом NumPy, который называется dtype (тип-данных)). Каждый ndarray ассоциирован только с одним типом dtype.
* размер массива фиксирован, а это значит, что после создания объекта его уже нельзя поменять. Это поведение отличается от такового у списков Python, которые могут увеличиваться и уменьшаться в размерах.


Основные атрибуты объекта numpy.ndarray в Python:

1. .shape: Это кортеж, показывающий размеры массива по каждой оси. В данном случае (3, 5), что означает 3 строки и 5 столбцов.

2. .ndim: Количество измерений или осей массива. Здесь 2, так как массив двумерный.

3. .dtype: Тип данных элементов массива. В этом примере int32, что означает 32-битное целое число.

4. .itemsize: Размер каждого элемента в байтах. Здесь 4 байта, что соответствует типу int32.

5. .size: Общее количество элементов в массиве. В данном случае 15 (3 * 5).




**Создание ndarray**

Конвертация python-объектов

In [3]:
np.array([1, 2, 3, 4]) # одномерный массив

array([1, 2, 3, 4])

In [4]:
a = np.array([[1, 2], [3, 4]]) # двумерный массив

Использование внутренних функций NumPy

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(2, 10, 0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5, 9. , 9.5])

In [7]:
np.eye(3) #  Используется в линейной алгебре и матричных вычислениях.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.zeros((2, 3)) #Полезна для инициализации массивов перед вычислениями.

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2, 3)) # Часто используется в математических операциях.

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.random.rand(3, 2) # Полезна для статистических расчетов, симуляций и инициализации весов в машинном обучении.

array([[0.17726262, 0.47049182],
       [0.3376185 , 0.38136018],
       [0.55130379, 0.47545845]])

Эти функции важны для:

1. Быстрой инициализации массивов с определенными свойствами
2. Создания тестовых данных
3. Выполнения матричных операций
4. Работы с алгоритмами машинного обучения и статистики

Они позволяют эффективно создавать структурированные данные для различных научных и инженерных задач.

**Обращение по индексу**

In [6]:
np_array = np.array([1, 2, 3, 4])
np_array[1]

2

In [7]:
np_array = np.array([[1, 2], [3, 4]])
np_array

array([[1, 2],
       [3, 4]])

In [8]:
np_array[1]

array([3, 4])

In [9]:
np_array[1, 0]

3

In [10]:
np_array[1][0]

3

`np_array[1, 0] == np_array[1][0]`, однако второй вариант менее эффективен, так как после обращения по первому индексу создается новый временный массив

**Срезы (слайсинг)**

`item[START:STOP:STEP]` - берёт срез от номера START, до STOP (не включая его), с шагом STEP.

In [11]:
np_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np_array[:5]

array([0, 1, 2, 3, 4])

In [17]:
np_array[1:6:2]

array([1, 3, 5])

In [18]:
np_array[-3:-1]

array([7, 8])

#### Характеристики массива

In [12]:
np_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np_array.ndim

1

In [14]:
x = np.array([[1, 1],
              [0, 1]])
x.shape

(2, 2)

In [15]:
x.ndim

2

In [23]:
x.size

4

In [29]:
x1 = np_array.reshape(2, 5)
x1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
np_array.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [18]:
x1.shape

(2, 5)

In [27]:
x2 = np_array.reshape(1, -1)
x2

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [24]:
x2.shape

(2, 5)

#### Базовые операции

In [30]:
np_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np_array + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
np_array * 10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [32]:
np_array ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [35]:
x = np.arange(0, 100, 10)
x

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
x - np_array

array([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81])

In [37]:
np.sin(np_array)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [38]:
np_array *= 2
np_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
x = np.array([[2, 0],
              [3, 4]])
x.min()

0

In [41]:
x.max()

4

In [43]:
x.argmax()

3

In [44]:
x.mean()

2.25

In [47]:
x.mean(axis=0)

array([2.5, 2. ])

In [48]:
x.mean(axis=1)

array([1. , 3.5])

Операции с матрицами

In [49]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

A * B # поэлементное произведение

array([[2, 0],
       [0, 4]])

In [50]:
A @ B # матричное произведение, python >= 3.5

array([[5, 4],
       [3, 4]])

In [51]:
A.dot(B) # матричное произведение

array([[5, 4],
       [3, 4]])

In [52]:
A.dot(B).T

array([[5, 3],
       [4, 4]])

#### Соединение/разбиение массивов

In [53]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

vstack_result = np.vstack((A, B))
vstack_result

array([[1, 1],
       [0, 1],
       [2, 0],
       [3, 4]])

In [54]:
hstack_result = np.hstack((A, B))
hstack_result

array([[1, 1, 2, 0],
       [0, 1, 3, 4]])

In [55]:
np.vsplit(vstack_result, 2)

[array([[1, 1],
        [0, 1]]),
 array([[2, 0],
        [3, 4]])]

In [56]:
np.hsplit(hstack_result, 2)

[array([[1, 1],
        [0, 1]]),
 array([[2, 0],
        [3, 4]])]

#### Массивы случайных значений

np.random.sample - массив заданной формы, состоящий из чисел, взятых из равномерного распределения на отрезке $[0, 1)$.

In [57]:
a = np.random.sample((3, 4)) # на вход подается кортеж

print(a)

[[0.44326773 0.03705781 0.43074527 0.35676952]
 [0.75317897 0.66023128 0.7631963  0.10587961]
 [0.61609483 0.34952678 0.07891    0.76743072]]


In [58]:
print(f"Одно значение: {np.random.sample()}")

print(f"Пять значениий: {np.random.sample(5)}")

Одно значение: 0.16012650526804706
Пять значениий: [0.21433229 0.3998508  0.73590347 0.89461656 0.68988399]


np.random.randn - массив, взятый из нормального распределения (со средним $0$ и среднеквадратическим отклонением $1$):

In [59]:
b = np.random.randn(3, 4) # не кортеж, а последовательность размеров по каждому измерению.

print(b)

[[-1.45627219  0.20184679  0.68984463 -0.24620813]
 [ 0.04514977  0.66433045 -1.23476554 -1.18453191]
 [-1.25039506 -1.11606473 -0.81282904 -1.53974618]]


np.random.randint - возвращает массив из целых чисел в указанном диапазоне:

In [72]:
c = np.random.randint(0, 4, (3, 4))

print(c)

[[3 2 1 2]
 [2 3 0 1]
 [0 2 3 3]]


np.random.choice - возвращает случайно выбранные элементы из заранее заданного массива:

In [73]:
A = np.arange(-10, 0)
A

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [75]:
d = np.random.choice(A, (3, 4))

print(d)

[[-4 -9 -7 -6]
 [-5 -5 -5 -5]
 [-7 -9 -2 -8]]


#### Статистические функции

Вот несколько методов, позволяющих вычислить различные статистики массива `a`:

* `a.min` - минимальное значение
* `a.max` - максимальное значение
* `a.mean` - среднее значение
* `a.std` - среднее квадратическое отклонение

Все эти значения считаются по всему массиву, либо вдоль определённой оси, если задан параметр `axis`.

In [76]:
print(a)

[[0.44326773 0.03705781 0.43074527 0.35676952]
 [0.75317897 0.66023128 0.7631963  0.10587961]
 [0.61609483 0.34952678 0.07891    0.76743072]]


In [79]:
print("Минимальное значение: {}".format(a.min()))

print("Средние значения строк: {}".format(a.mean(axis=1)))

print("Средние квадратические отклонения столбцов: {}".format(a.mean(axis=0)))

Минимальное значение: 0.03705780544574422
Средние значения строк: 0.4468573999998653
Средние квадратические отклонения столбцов: [0.60418051 0.34893862 0.42428385 0.41002662]


#### Запись и чтение массивов из файла



In [58]:
np.save("a.npy", a)

Для чтения из файла используется функция `np.load`:

In [59]:
a = np.load("a.npy")